# Generated by Django 6.0.5 on 2026-05-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
