# Generated by Django 6.0.5 on 2026-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0005_brands_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
